# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui',
# licensing of 'main.ui' applies.
#
# Created: Mon Jan 28 22:22:49 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(446, 535)
        self.centralwidget = QtWidgets.QWidget(Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblPassword = QtWidgets.QLabel(self.frame)
        self.lblPassword.setObjectName("lblPassword")
        self.gridLayout_2.addWidget(self.lblPassword, 3, 0, 1, 1)
        self.ledLogin = QtWidgets.QLineEdit(self.frame)
        self.ledLogin.setObjectName("ledLogin")
        self.gridLayout_2.addWidget(self.ledLogin, 2, 1, 1, 1)
        self.ledPassword = QtWidgets.QLineEdit(self.frame)
        self.ledPassword.setObjectName("ledPassword")
        self.gridLayout_2.addWidget(self.ledPassword, 3, 1, 1, 1)
        self.lblLogin = QtWidgets.QLabel(self.frame)
        self.lblLogin.setObjectName("lblLogin")
        self.gridLayout_2.addWidget(self.lblLogin, 2, 0, 1, 1)
        self.lswMain = QtWidgets.QListWidget(self.frame)
        self.lswMain.setObjectName("lswMain")
        self.gridLayout_2.addWidget(self.lswMain, 1, 0, 1, 2)
        self.listView = QtWidgets.QListView(self.frame)
        self.listView.setObjectName("listView")
        self.gridLayout_2.addWidget(self.listView, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 2)
        self.btnAdd = QtWidgets.QPushButton(self.frame)
        self.btnAdd.setObjectName("btnAdd")
        self.gridLayout_3.addWidget(self.btnAdd, 1, 0, 1, 1)
        self.btnClear = QtWidgets.QPushButton(self.frame)
        self.btnClear.setObjectName("btnClear")
        self.gridLayout_3.addWidget(self.btnClear, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        Main.setCentralWidget(self.centralwidget)
        self.mnbMain = QtWidgets.QMenuBar(Main)
        self.mnbMain.setGeometry(QtCore.QRect(0, 0, 446, 22))
        self.mnbMain.setObjectName("mnbMain")
        self.mnuFile = QtWidgets.QMenu(self.mnbMain)
        self.mnuFile.setObjectName("mnuFile")
        self.mnuHelp = QtWidgets.QMenu(self.mnbMain)
        self.mnuHelp.setObjectName("mnuHelp")
        Main.setMenuBar(self.mnbMain)
        self.stbMain = QtWidgets.QStatusBar(Main)
        self.stbMain.setObjectName("stbMain")
        Main.setStatusBar(self.stbMain)
        self.toolBar = QtWidgets.QToolBar(Main)
        self.toolBar.setObjectName("toolBar")
        Main.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actOpen = QtWidgets.QAction(Main)
        self.actOpen.setObjectName("actOpen")
        self.actionClose = QtWidgets.QAction(Main)
        self.actionClose.setObjectName("actionClose")
        self.actExit = QtWidgets.QAction(Main)
        self.actExit.setObjectName("actExit")
        self.actAbout = QtWidgets.QAction(Main)
        self.actAbout.setObjectName("actAbout")
        self.mnuFile.addAction(self.actOpen)
        self.mnuFile.addSeparator()
        self.mnuFile.addAction(self.actExit)
        self.mnuHelp.addAction(self.actAbout)
        self.mnbMain.addAction(self.mnuFile.menuAction())
        self.mnbMain.addAction(self.mnuHelp.menuAction())

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        Main.setWindowTitle(QtWidgets.QApplication.translate("Main", "My First App", None, -1))
        self.lblPassword.setText(QtWidgets.QApplication.translate("Main", "Password", None, -1))
        self.lblLogin.setText(QtWidgets.QApplication.translate("Main", "Login", None, -1))
        self.btnAdd.setText(QtWidgets.QApplication.translate("Main", "Add", None, -1))
        self.btnClear.setText(QtWidgets.QApplication.translate("Main", "Clear", None, -1))
        self.mnuFile.setTitle(QtWidgets.QApplication.translate("Main", "File", None, -1))
        self.mnuHelp.setTitle(QtWidgets.QApplication.translate("Main", "Help", None, -1))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("Main", "toolBar", None, -1))
        self.actOpen.setText(QtWidgets.QApplication.translate("Main", "Open", None, -1))
        self.actionClose.setText(QtWidgets.QApplication.translate("Main", "Close", None, -1))
        self.actExit.setText(QtWidgets.QApplication.translate("Main", "Exit", None, -1))
        self.actAbout.setText(QtWidgets.QApplication.translate("Main", "About", None, -1))

