# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui',
# licensing of 'gui.ui' applies.
#
# Created: Thu Jan 31 18:22:57 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(515, 517)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frm_Main = QtWidgets.QFrame(self.centralwidget)
        self.frm_Main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_Main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_Main.setObjectName("frm_Main")
        self.gridLayout = QtWidgets.QGridLayout(self.frm_Main)
        self.gridLayout.setObjectName("gridLayout")
        self.frm_Rigth = QtWidgets.QFrame(self.frm_Main)
        self.frm_Rigth.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_Rigth.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_Rigth.setObjectName("frm_Rigth")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frm_Rigth)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lsw_main = QtWidgets.QListWidget(self.frm_Rigth)
        self.lsw_main.setObjectName("lsw_main")
        self.gridLayout_6.addWidget(self.lsw_main, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frm_Rigth, 0, 0, 1, 1)
        self.frm_Left = QtWidgets.QFrame(self.frm_Main)
        self.frm_Left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_Left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_Left.setObjectName("frm_Left")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frm_Left)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frm_ = QtWidgets.QFrame(self.frm_Left)
        self.frm_.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_.setObjectName("frm_")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frm_)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbl_name = QtWidgets.QLabel(self.frm_)
        self.lbl_name.setObjectName("lbl_name")
        self.gridLayout_3.addWidget(self.lbl_name, 0, 0, 1, 1)
        self.led_name = QtWidgets.QLineEdit(self.frm_)
        self.led_name.setObjectName("led_name")
        self.gridLayout_3.addWidget(self.led_name, 0, 1, 1, 1)
        self.lbl_color = QtWidgets.QLabel(self.frm_)
        self.lbl_color.setObjectName("lbl_color")
        self.gridLayout_3.addWidget(self.lbl_color, 1, 0, 1, 1)
        self.led_color = QtWidgets.QLineEdit(self.frm_)
        self.led_color.setObjectName("led_color")
        self.gridLayout_3.addWidget(self.led_color, 1, 1, 1, 1)
        self.lbl_size = QtWidgets.QLabel(self.frm_)
        self.lbl_size.setObjectName("lbl_size")
        self.gridLayout_3.addWidget(self.lbl_size, 2, 0, 1, 1)
        self.led_size = QtWidgets.QLineEdit(self.frm_)
        self.led_size.setObjectName("led_size")
        self.gridLayout_3.addWidget(self.led_size, 2, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frm_, 0, 0, 1, 1)
        self.frm_Bottons = QtWidgets.QFrame(self.frm_Left)
        self.frm_Bottons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_Bottons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_Bottons.setObjectName("frm_Bottons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frm_Bottons)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbt_add = QtWidgets.QPushButton(self.frm_Bottons)
        self.pbt_add.setObjectName("pbt_add")
        self.horizontalLayout.addWidget(self.pbt_add)
        self.pbt_delete = QtWidgets.QPushButton(self.frm_Bottons)
        self.pbt_delete.setObjectName("pbt_delete")
        self.horizontalLayout.addWidget(self.pbt_delete)
        self.pbt_update = QtWidgets.QPushButton(self.frm_Bottons)
        self.pbt_update.setObjectName("pbt_update")
        self.horizontalLayout.addWidget(self.pbt_update)
        self.gridLayout_5.addWidget(self.frm_Bottons, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frm_Left, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frm_Main, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 515, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.lbl_name.setText(QtWidgets.QApplication.translate("MainWindow", "Name", None, -1))
        self.lbl_color.setText(QtWidgets.QApplication.translate("MainWindow", "Color", None, -1))
        self.lbl_size.setText(QtWidgets.QApplication.translate("MainWindow", "Size", None, -1))
        self.pbt_add.setText(QtWidgets.QApplication.translate("MainWindow", "Add", None, -1))
        self.pbt_delete.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.pbt_update.setText(QtWidgets.QApplication.translate("MainWindow", "Update", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("MainWindow", "Exit", None, -1))

